// <auto-generated />
using System;
using Maplr.SuggarShack.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Maplr.SuggarShack.Data.Migrations
{
    [DbContext(typeof(MaplrContext))]
    [Migration("20230405022628_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Maplr.SuggarShack.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Maplr.SuggarShack.Domain.Entities.OrderItems", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Maplr.SuggarShack.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("070356bc-fa7b-49b5-9efa-37c6be8376b7"),
                            Description = "Fine nose that opens to the scents of maple and a quite supported final. In mouth, it has a pure taste and an ample texture, unveiling fully the maple aromas.",
                            Image = "https://www.camaplepremium.com/wp-content/uploads/2017/11/Sirop_amber_250ml-800x533.jpg",
                            Name = "AMBER MAPLE SYRUP",
                            Price = 12.949999999999999,
                            Stock = 100,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("a3f94f7c-2f43-4299-a02f-26f04f8e0929"),
                            Description = "Strong nose that opens on a caramel and butter perfume. In mouth, a franc maple flavor and a creamy texture.",
                            Image = "https://www.camaplepremium.com/wp-content/uploads/2018/05/Sirop_dark_100ml.jpg",
                            Name = "DARK MAPLE SYRUP",
                            Price = 7.9500000000000002,
                            Stock = 100,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("b241f0d7-a7e9-41dd-8f0a-bab78056e673"),
                            Description = "Soft nose that opens on a caramel and butter perfume. In mouth, a franc maple flavor and a creamy texture.",
                            Image = "https://www.finemapleproducts.com/wp-content/uploads/2018/06/803_2461.jpg",
                            Name = "CLEAR MAPLE SYRUP",
                            Price = 6.9500000000000002,
                            Stock = 100,
                            Type = 2
                        });
                });

            modelBuilder.Entity("Maplr.SuggarShack.Domain.Entities.OrderItems", b =>
                {
                    b.HasOne("Maplr.SuggarShack.Domain.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Maplr.SuggarShack.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Maplr.SuggarShack.Domain.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
