apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maplrservice
  template:
    metadata:
      labels:
        app: maplrservice
    spec:
      containers:
        - name: maplrservice
          image: dockoliveira/suggarshackapi:latest
---
apiVersion: v1
kind: Service
metadata:
  name: maplr-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: maplrservice
  ports:
    - name: maplrservice
      protocol: TCP
      port: 80
      targetPort: 80